#!/usr/bin/env node
/**
 * Generates a Docsify `_sidebar.md` from a `docs/` folder, using the same rules as the
 * acro-docs site (acronym-lol/acro-docs, scripts/lib/nav.ts), so a page sits in the same
 * place with the same title on a repo's GitHub Pages site as on acro-docs.
 *
 *   acro-docs-sidebar [docs-dir] [--check] [--stdout]     (bin/acro-docs-sidebar.mjs)
 *
 * --check   exit 1 (and print a diff summary) if docs-dir/_sidebar.md is out of date
 * --stdout  print the sidebar instead of writing it
 *
 * THE RULES, and why each one is here:
 *
 *   Pages       .md files. Files or folders starting with `_` are skipped (that is how
 *               _meta.yml and _sidebar.md stay out), and so are dotfiles.
 *   Titles      sidebar_label, then title, then the first `# ` heading, then the
 *               filename humanised. The same precedence as Docusaurus and acro-docs.
 *   Order       sidebar_position ascending (decimals allowed), then filename. A folder's
 *               position comes from its _category_.json.
 *   Folders     a folder's README.md or index.md is the folder's own page, not a child.
 *               Its label is _category_.json's label, then that page's title, then the
 *               folder name exactly as written. A folder holding no pages is dropped.
 *   Root page   the root README is the site's home page. Docsify links to it from the
 *               site name at the top of the rail, so it is not listed again, just as
 *               acro-docs shows the repo name rather than a "README" entry.
 *
 * Zero dependencies on purpose: it runs from a reusable workflow and via `npx` straight
 * from GitHub, where an install step is one more thing to break. The frontmatter reader
 * handles the subset these fields use (scalars, quoted or not) and nothing more.
 */

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT_INDEX = new Set(['readme.md', 'index.md']);
const BANNER_PREFIX = '<!-- generated by acro-docs-theme';
export const EXTRA_FILE = '_sidebar.extra.md';

// ---------------------------------------------------------------------------- reading

/**
 * Frontmatter as a flat map of the scalar keys. Returns {} when there is none.
 * Tolerates a UTF-8 BOM, which files edited on Windows do carry, and CRLF line endings.
 */
export function parseFrontmatter(source) {
  const text = source.replace(/^﻿/, '');
  const match = /^---[ \t]*\r?\n([\s\S]*?)\r?\n---[ \t]*(?:\r?\n|$)/.exec(text);
  if (!match) return {};
  const out = {};
  for (const line of match[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z_][\w-]*)[ \t]*:[ \t]*(.*?)[ \t]*$/.exec(line);
    if (!kv) continue;
    out[kv[1]] = unquote(kv[2]);
  }
  return out;
}

function unquote(raw) {
  if (raw.length >= 2 && raw[0] === '"' && raw.at(-1) === '"') {
    return raw.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\');
  }
  if (raw.length >= 2 && raw[0] === "'" && raw.at(-1) === "'") {
    return raw.slice(1, -1).replace(/''/g, "'");
  }
  // An unquoted value can carry a trailing comment: `sidebar_position: 2 # after intro`.
  return raw.replace(/\s+#.*$/, '');
}

function stripFrontmatter(source) {
  return source.replace(/^﻿/, '').replace(/^---[ \t]*\r?\n[\s\S]*?\r?\n---[ \t]*(?:\r?\n|$)/, '');
}

/** The first ATX H1 in the body, as acro-docs and Docusaurus take it. */
export function firstHeading(source) {
  const m = /^#[ \t]+(.+?)[ \t]*#*[ \t]*$/m.exec(stripFrontmatter(source));
  return m ? m[1].trim() || null : null;
}

/** `getting-started` -> `Getting started`. Last resort only. */
export function humanise(name) {
  const spaced = name.replace(/[-_]+/g, ' ').trim();
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

function nonEmpty(value) {
  return typeof value === 'string' && value.trim() !== '' ? value.trim() : null;
}

function positionOf(value) {
  const n = typeof value === 'number' ? value : Number(value);
  return value !== undefined && value !== '' && Number.isFinite(n) ? n : Number.POSITIVE_INFINITY;
}

function pageMeta(file, slug) {
  const source = readFileSync(file, 'utf8');
  const fm = parseFrontmatter(source);
  return {
    label:
      nonEmpty(fm.sidebar_label) ?? nonEmpty(fm.title) ?? firstHeading(source) ?? humanise(slug),
    position: positionOf(fm.sidebar_position),
  };
}

function categoryMeta(dir) {
  const file = path.join(dir, '_category_.json');
  if (!existsSync(file)) return { label: null, position: Number.POSITIVE_INFINITY };
  try {
    const raw = JSON.parse(readFileSync(file, 'utf8'));
    return { label: nonEmpty(raw.label), position: positionOf(raw.position) };
  } catch {
    // A malformed _category_.json should not break the sidebar; acro-docs falls back the
    // same way.
    return { label: null, position: Number.POSITIVE_INFINITY };
  }
}

// ---------------------------------------------------------------------------- the tree

/**
 * Walks `dir` into nodes of { label, href, children }. `href` is a Docsify route
 * relative to the docs root, or null for a folder with no page of its own.
 *
 * Docsify loads `folder/` as `folder/README.md`, spelled exactly that way, and GitHub
 * Pages is case-sensitive. So a folder page linked as `folder/` must really be
 * README.md; an index.md or readme.md is linked by its own name instead.
 */
export function walk(dir, prefix = '') {
  const nodes = [];

  for (const name of readdirSync(dir)) {
    if (name.startsWith('_') || name.startsWith('.')) continue;
    const abs = path.join(dir, name);
    const rel = prefix ? `${prefix}/${name}` : name;

    if (statSync(abs).isDirectory()) {
      const children = walk(abs, rel);
      if (children.length === 0) continue;
      const own = children.find((c) => c.isIndex);
      const meta = categoryMeta(abs);
      nodes.push({
        label: meta.label ?? own?.label ?? name,
        href: own?.href ?? null,
        children: children.filter((c) => c !== own),
        position: meta.position,
        sortKey: name.toLowerCase(),
      });
      continue;
    }

    if (!name.toLowerCase().endsWith('.md')) continue;
    const slug = name.slice(0, -3);
    const isIndex = ROOT_INDEX.has(name.toLowerCase());
    const meta = pageMeta(abs, slug);
    nodes.push({
      label: meta.label,
      href: isIndex
        ? name === 'README.md'
          ? prefix
            ? `${prefix}/`
            : '/'
          : rel.slice(0, -3)
        : rel.slice(0, -3),
      children: [],
      isIndex,
      position: meta.position,
      // An index sorts first: it is the page its folder represents.
      sortKey: isIndex ? '' : slug.toLowerCase(),
    });
  }

  nodes.sort((a, b) => a.position - b.position || a.sortKey.localeCompare(b.sortKey));
  return nodes.map(({ label, href, children, isIndex }) => ({
    label,
    href,
    children,
    isIndex: !!isIndex,
  }));
}

// ---------------------------------------------------------------------------- writing

/** `[` and `]` in a label would end the link text early. */
function escapeLabel(label) {
  return label.replace(/([\\[\]])/g, '\\$1');
}

function render(nodes, depth) {
  const indent = '  '.repeat(depth);
  const lines = [];
  for (const node of nodes) {
    const text = node.href ? `[${escapeLabel(node.label)}](${node.href})` : `**${node.label}**`;
    lines.push(`${indent}- ${text}`);
    if (node.children.length) lines.push(...render(node.children, depth + 1));
  }
  return lines;
}

export function buildSidebar(docsDir, version = 'dev') {
  // The root README/index is the home page, reached from the site name. Only the root's:
  // a folder's index was already folded into that folder by walk().
  const nodes = walk(docsDir).filter((n) => !n.isIndex);

  const parts = [
    `${BANNER_PREFIX} ${version}. Do not edit: it is rewritten from the docs/ folder.`,
    `     To add links of your own (other repos, external pages), put them in ${EXTRA_FILE}. -->`,
    '',
    ...render(nodes, 0),
  ];

  const extraFile = path.join(docsDir, EXTRA_FILE);
  if (existsSync(extraFile)) {
    const extra = readFileSync(extraFile, 'utf8').replace(/^﻿/, '').trim();
    if (extra) parts.push('', '---', '', extra);
  }
  return `${parts.join('\n')}\n`;
}

// ---------------------------------------------------------------------------- cli

function readVersion() {
  try {
    const pkg = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'package.json');
    return `v${JSON.parse(readFileSync(pkg, 'utf8')).version}`;
  } catch {
    return 'dev';
  }
}

/** Commands in messages are pasted into shells, so print them with forward slashes on every OS. */
function toPosix(p) {
  return p.split(path.sep).join('/');
}

/** The banner carries the version; comparing without it keeps upgrades from reading as drift. */
function withoutBanner(text) {
  return text.replace(/^<!-- generated by acro-docs-theme[\s\S]*?-->\n/, '');
}

/**
 * `acro-docs-sidebar [folder...] [--check|--stdout]`. Each folder gets its own sidebar, so a
 * repo that hosts several sites (e.g. one per git subtree) regenerates them all in one run.
 * Every folder is processed even if one fails; the exit code is the worst of them.
 */
export function main(argv) {
  const flags = new Set(argv.filter((a) => a.startsWith('--')));
  const folders = argv.filter((a) => !a.startsWith('--'));
  if (folders.length === 0) folders.push('docs');
  if (flags.has('--stdout') && folders.length > 1) {
    console.error('acro-docs-sidebar: --stdout takes a single folder.');
    return 2;
  }
  return folders.reduce((worst, folder) => Math.max(worst, runFolder(folder, flags)), 0);
}

function runFolder(folder, flags) {
  const docsDir = path.resolve(folder);

  if (!existsSync(docsDir) || !statSync(docsDir).isDirectory()) {
    console.error(`acro-docs-sidebar: ${docsDir} is not a folder. Pass docs folders as arguments.`);
    return 2;
  }

  const sidebar = buildSidebar(docsDir, readVersion());
  const target = path.join(docsDir, '_sidebar.md');

  if (flags.has('--stdout')) {
    process.stdout.write(sidebar);
    return 0;
  }

  if (flags.has('--check')) {
    const current = existsSync(target) ? readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : '';
    if (withoutBanner(current) === withoutBanner(sidebar)) {
      console.log(
        `acro-docs-sidebar: ${toPosix(path.relative(process.cwd(), target)) || target} is up to date.`,
      );
      return 0;
    }
    console.error(
      `acro-docs-sidebar: ${target} is out of date. Run \`npx -p github:acronym-lol/acro-docs-theme#v1 acro-docs-sidebar ${toPosix(path.relative(process.cwd(), docsDir)) || '.'}\` and commit the result.`,
    );
    return 1;
  }

  const existing = existsSync(target) ? readFileSync(target, 'utf8') : null;
  if (existing !== null && !existing.startsWith(BANNER_PREFIX)) {
    // A hand-written sidebar is being replaced. Say so once, so nobody is surprised that
    // their manual links moved; MIGRATING.md explains where they go (_sidebar.extra.md).
    console.warn(
      `acro-docs-sidebar: replacing a hand-written ${target}. Move any extra links to ${EXTRA_FILE}.`,
    );
  }
  writeFileSync(target, sidebar);
  console.log(`acro-docs-sidebar: wrote ${target}`);
  return 0;
}
